### ISSUE TITLE
NullException after login in 7.1

### ISSUE THREAD

**Issue by Infiziert90** [MidoriKami/SortaKinda#34] opened 2024-11-17 19:41 UTC
Must have happend around 1-2 Minutes after logging in, can't say 100% what i did at that point

```cs
20:10:56.710 | ERR | [GameInventoryPluginScoped] ["SortaKinda"] Exception during "InventoryChanged" callback
    System.ArgumentNullException: Value cannot be null. (Parameter 'source')
       at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
       at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
       at SortaKinda.Controllers.ModuleController.<>c__DisplayClass7_0.<InventoryChanged>b__0(InventoryType type) in /work/repo/SortaKinda/Controllers/ModuleController.cs:line 63
       at System.Collections.Generic.HashSet`1.RemoveWhere(Predicate`1 match)
       at SortaKinda.Controllers.ModuleController.InventoryChanged(IReadOnlyCollection`1 events) in /work/repo/SortaKinda/Controllers/ModuleController.cs:line 63
       at Dalamud.Game.Inventory.GameInventoryPluginScoped.InvokeChanged(IReadOnlyCollection`1 data) in C:\goatsoft\companysecrets\dalamud\\Game\Inventory\GameInventory.cs:line 438
```

**Comment by Infiziert90** [comment] 2024-11-17 20:10
Log was empty otherwise, can't tell you anymore sadly

**Comment by MidoriKami** [comment] 2024-11-18 18:51
Hmm, might be a safety check we need to add to dalamud, if the events are triggering on a null player?

**Comment by MidoriKami** [comment] 2024-11-19 01:45
Unable to reproduce. Closing as non-important issue.

**Closed by MidoriKami** 2024-11-19 01:45 UTC
